stages:
  - test
  - deploy

image: edd01:5000/eddbase:latest


.production:
  image: edd01:5000/eddbase
  before_script:
    - apt-get -y update && apt-get install -y python-ipaddress python-coverage

.python3:
  image: nvidia/cuda:10.2-devel-ubuntu18.04
  before_script:
    - apt-get -y update && apt-get install -y python3-pip python3-pybind11 git #libboost-program-options-dev libboost-system-dev
    - pip3 install katcp redis coloredlogs numpy #spead2 



test_production_base:
  stage: test
  extends: .production
  script:
    - python-coverage run  -p --omit "*/site-packages/*,*test*" --source="mpikat" test.py
  only:
    - pushes
    - merge_requests
  artifacts:
    untracked: true
    when: always

test_python3:
  stage: test
  extends: .python3
  script:
    - python3 test.py
  only:
    - pushes
    - merge_requests



test_production_gated:
  image: edd01:5000/edd_gated_stokes
  extends: .production
  stage: test
  script:
    - cp testing_tools/dummy_numa_ctl.py /usr/bin/numactl
    - touch mpikat/effelsberg/edd/pipeline/test/__init__.py
    - python setup.py install
    - python-coverage run -p --omit "*/site-packages/*,*test*" --source="mpikat" mpikat/effelsberg/edd/pipeline/test/testGatedPipeline.py
  only:
    - pushes
    - merge_requests
  artifacts:
    untracked: true
    when: always


    #test_coverage:
    #  stage: deploy
    #  dependencies:
    #    - test_production_gated
    #    - test_production_base
    #  script:
    #    - python2-coverage xml
    #  artifacts:
    #    reports:
    #      cobertura: coverage.xml
    #  when: on_success


test_debug_output:
  stage: deploy
  script:
    - cat debug.log
  when: on_failure


pages:
  stage: deploy
  extends: .production
  dependencies:
    - test_production_gated
    - test_production_base
  script:
    - touch mpikat/effelsberg/edd/pipeline/test/__init__.py
    - ls -a
    - python-coverage combine .coverage*
    - ls -a
    - python-coverage html
    - python-coverage report
    - mkdir public
    - mv htmlcov/ public/coverage
  artifacts:
    paths:
      - public
  only:
    - dev
    - cicd
