image: edd01:5000/eddbase:latest

before_script:
  - apt-get install python-ipaddress

execute_unit_tests:
  script:
    - ./test.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'

